apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  labels:
    app: bookshelf
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  selector:
    app: bookshelf
