apiVersion: batch/v1
kind: Job
metadata:
  name: import-books
spec:
  template:
    spec:
      containers:
      - name: import-books
        image: public.ecr.aws/prima/bookshelf-remove-after-lab:2.0.0
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASS
        - name: TZ
          value: Europe/Rome
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["python3"]
        args: ["import.py"]
      restartPolicy: Never
  backoffLimit: 4
